# Generated by Django 3.2.7 on 2021-09-23 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Repuestos', '0001_initial'),
        ('Reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('IDpresupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('Diagnostico', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField()),
                ('Total', models.IntegerField()),
                ('Repuesto', models.ManyToManyField(to='Repuestos.Repuesto')),
                ('Reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reservas.reserva')),
            ],
        ),
    ]
