# Generated by Django 3.2.7 on 2021-09-26 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='Total',
        ),
    ]
