# Generated by Django 3.1 on 2021-10-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Repuestos', '0001_initial'),
        ('Presupuestos', '0002_remove_presupuesto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='Repuesto',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='Repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Repuestos.repuesto'),
        ),
    ]
