# Generated by Django 3.2.7 on 2021-09-23 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('IDBoleta', models.AutoField(primary_key=True, serialize=False)),
                ('Presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Presupuestos.presupuesto')),
            ],
        ),
    ]
