# Generated by Django 3.2.7 on 2021-09-23 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cargos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('RutAministrador', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField()),
                ('Fechacontrato', models.DateField()),
                ('Cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cargos.cargo')),
            ],
        ),
    ]
